export const DEFAULT_VARIABLE_PERSONNEL_PASSWORD = "12345678";

export const VARIABLE_PERSONNEL = [
  { name: "Орлов Виктор Юрьевич", login: "orlov", initials: "ОВ" },
  { name: "Сидоров Андрей Сергеевич", login: "sidorov", initials: "СА" },
  { name: "Фетисов Даниил Юрьевич", login: "fetisov", initials: "ФД" },
  { name: "Чирич Максим Евгеньевич", login: "chirich", initials: "ЧМ" },
  { name: "Переслегин Дмитрий Петрович", login: "pereslegin", initials: "ПД" },
  { name: "Андреев Илья Андреевич", login: "andreev", initials: "АИ" },
  { name: "Артемов Егор Александрович", login: "artemov", initials: "АЕ" },
  { name: "Ваез Мохамед Владимир Юссефович", login: "vaez", initials: "ВМ" },
  { name: "Веремеев Павел Евгеньевич", login: "veremeev", initials: "ВП" },
  { name: "Дубровин Илья Сергеевич", login: "dubrovin", initials: "ДИ" },
  { name: "Леус Андрей Александрович", login: "leus", initials: "ЛА" },
  { name: "Распопов Кирилл Романович", login: "raspopov", initials: "РК" },
  { name: "Сацута Анатолий Игоревич", login: "satsuta", initials: "СА" },
  { name: "Бабенко Вячеслав Юрьевич", login: "babenko", initials: "БВ" },
  { name: "Мачнев Илья Алексеевич", login: "machnev", initials: "МИ" },
  { name: "Мухутдинов Булат Рамилевич", login: "mukhutdinov", initials: "МБ" },
  { name: "Сенченко Даниил Михайлович", login: "senchenko", initials: "СД" },
  { name: "Цветков Дмитрий Евгеньевич", login: "tsvetkov", initials: "ЦД" },
  { name: "Яковлев Юрий Александрович", login: "yakovlev", initials: "ЯЮ" },
  { name: "Талько Дмитрий Александрович", login: "talko", initials: "ТД" },
  { name: "Бабаев Алексей Сергеевич", login: "babaev", initials: "БА" },
  { name: "Баймаков Данил Алексеевич", login: "baymakov", initials: "БД" },
  { name: "Галданов Гэсэр Жамбалович", login: "galdanov", initials: "ГГ" },
  { name: "Дудин Артем Александрович", login: "dudin", initials: "ДА" },
  { name: "Казанцев Матвей Максимович", login: "kazantsev", initials: "КМ" },
  { name: "Каравацкий Дмитрий Андреевич", login: "karavatskiy", initials: "КД" },
  { name: "Киселев Андрей Юрьевич", login: "kiselev", initials: "КА" },
  { name: "Кистаев Семен Евгеньевич", login: "kistaev", initials: "КС" },
  { name: "Лаукарт Михаил Сергеевич", login: "laukart", initials: "ЛМ" },
  { name: "Литвинчев Артем Андреевич", login: "litvinchev", initials: "ЛА" },
  { name: "Поршаков Леонид Николаевич", login: "porshakov", initials: "ПЛ" },
  { name: "Ронжин Валерий Павлович", login: "ronzhin", initials: "РВ" },
  { name: "Седунов Никита Александрович", login: "sedunov", initials: "СН" },
  { name: "Селиверстов Кирилл Витальевич", login: "seliverstov", initials: "СК" },
  { name: "Ситников Иван Алексеевич", login: "sitnikov", initials: "СИ" },
  { name: "Сычев Данила Алексеевич", login: "sychev", initials: "СД" },
  { name: "Темиров Бадюрсолтан Темирович", login: "temirov", initials: "ТБ" },
  { name: "Ткачев Артем Валентинович", login: "tkachev", initials: "ТА" },
  { name: "Шингарев Александр Федорович", login: "shingarev", initials: "ША" },
  { name: "Яссер Марк Владимирович", login: "yasser", initials: "ЯМ" }
] as const;
